### ISSUE TITLE
npm run build fails 

### ISSUE THREAD

**Issue by lakamsani** [danfinlay/js-eth-personal-sign-examples#4]
I would like to experiment with this by making some changes. Not having luck trying to build it. 
node 8.9.4 and npm 5.6.0 on macOS Mojave.
```
ethsign git:(master) ✗ npm run build

> js-eth-personal-sign-examples@1.0.0 build /Users/vamsee/Development/blockchain/pulse/samples/js-eth-personal-sign-examples
> browserify -t brfs index.js -o bundle.js

Error: Cannot find module 'babel-runtime/regenerator' from '/Users/vamsee/Development/blockchain/pulse/samples/js-eth-personal-sign-examples/node_modules/ethjs-query/lib'
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! js-eth-personal-sign-examples@1.0.0 build: `browserify -t brfs index.js -o bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the js-eth-personal-sign-examples@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by lakamsani** [comment]
Fixed in this PR, thx. https://github.com/danfinlay/js-eth-personal-sign-examples/pull/3
